import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cnBgGradient = "bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-[#1e293b] via-[#020617] to-[#09090b]";

  return (
    <html lang="en">
      <body
        className={cn(`relative dark ${geistSans.variable} ${geistMono.variable} overscroll-none antialiased`, cnBgGradient)}
      >
        <header className="sticky max-w-7xl top-4 mx-auto z-10 p-4 rounded-xl backdrop-blur-md w-full bg-zinc-950/45 text-primary">
          <div className="flex items-center justify-between mx-4 font-[family-name:var(--font-geist-mono)]">
            <p>Mukhammad Fadhila Ikhsani</p>
          </div>
        </header>
        <main className="min-h-screen max-w-4xl w-full mx-auto">
          {children}
        </main>
        <footer></footer>
      </body>
    </html>
  );
}
